// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ssXJzNt8MiEu8LBoGu8nv3
// Component: wHca_GOFAh

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_scratch_pad.module.css'; // plasmic-import: ssXJzNt8MiEu8LBoGu8nv3/projectcss
import sty from './PlasmicBackBtn.module.css'; // plasmic-import: wHca_GOFAh/css

import ChevronLeftIcon from './icons/PlasmicIcon__ChevronLeft'; // plasmic-import: qcqo3gZMFJf/icon

export type PlasmicBackBtn__VariantMembers = {};
export type PlasmicBackBtn__VariantsArgs = {};
type VariantPropType = keyof PlasmicBackBtn__VariantsArgs;
export const PlasmicBackBtn__VariantProps = new Array<VariantPropType>();

export type PlasmicBackBtn__ArgsType = {};
type ArgPropType = keyof PlasmicBackBtn__ArgsType;
export const PlasmicBackBtn__ArgProps = new Array<ArgPropType>();

export type PlasmicBackBtn__OverridesType = {
  root?: p.Flex<'button'>;
  svg?: p.Flex<'svg'>;
  text?: p.Flex<'div'>;
};

export interface DefaultBackBtnProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicBackBtn__RenderFunc(props: {
  variants: PlasmicBackBtn__VariantsArgs;
  args: PlasmicBackBtn__ArgsType;
  overrides: PlasmicBackBtn__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <button
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
      )}
    >
      <ChevronLeftIcon
        data-plasmic-name={'svg'}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={'img'}
      />

      <div
        data-plasmic-name={'text'}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {'Back'}
      </div>
    </button>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'svg', 'text'],
  svg: ['svg'],
  text: ['text'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'button';
  svg: 'svg';
  text: 'div';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBackBtn__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBackBtn__VariantsArgs;
    args?: PlasmicBackBtn__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBackBtn__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBackBtn__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>,
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBackBtn__ArgProps,
          internalVariantPropNames: PlasmicBackBtn__VariantProps,
        }),
      [props, nodeName],
    );
    return PlasmicBackBtn__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicBackBtn';
  } else {
    func.displayName = `PlasmicBackBtn.${nodeName}`;
  }
  return func;
}

export const PlasmicBackBtn = Object.assign(
  // Top-level PlasmicBackBtn renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent('svg'),
    text: makeNodeComponent('text'),

    // Metadata about props expected for PlasmicBackBtn
    internalVariantProps: PlasmicBackBtn__VariantProps,
    internalArgProps: PlasmicBackBtn__ArgProps,
  },
);

export default PlasmicBackBtn;
/* prettier-ignore-end */
