// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ssXJzNt8MiEu8LBoGu8nv3
// Component: 5s-JvrYMxR

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import _1099 from '../../_1099'; // plasmic-import: 61CShZt2qP/component

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_scratch_pad.module.css'; // plasmic-import: ssXJzNt8MiEu8LBoGu8nv3/projectcss
import sty from './PlasmicW2.module.css'; // plasmic-import: 5s-JvrYMxR/css

import Group379Icon from './icons/PlasmicIcon__Group379'; // plasmic-import: x-Q6VRzLqHf/icon
import icnW2DfFc8LaUgl from './images/icnW2.svg'; // plasmic-import: dfFC8LaUgl/picture

export type PlasmicW2__VariantMembers = {
  icon: 'w2' | '_1099';
};
export type PlasmicW2__VariantsArgs = {
  icon?: SingleChoiceArg<'w2' | '_1099'>;
};
type VariantPropType = keyof PlasmicW2__VariantsArgs;
export const PlasmicW2__VariantProps = new Array<VariantPropType>('icon');

export type PlasmicW2__ArgsType = {};
type ArgPropType = keyof PlasmicW2__ArgsType;
export const PlasmicW2__ArgProps = new Array<ArgPropType>();

export type PlasmicW2__OverridesType = {
  root?: p.Flex<'div'>;
  img?: p.Flex<'img'>;
  icnChair2?: p.Flex<'div'>;
  _1099?: p.Flex<typeof _1099>;
  svg?: p.Flex<'svg'>;
};

export interface DefaultW2Props {
  icon?: SingleChoiceArg<'w2' | '_1099'>;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicW2__RenderFunc(props: {
  variants: PlasmicW2__VariantsArgs;
  args: PlasmicW2__ArgsType;
  overrides: PlasmicW2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: 'icon',
        type: 'private',
        variableType: 'variant',
        initFunc: true
          ? ({ $props, $state, $queries, $ctx }) => $props.icon
          : undefined,
      },
    ],
    [$props, $ctx],
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  return (
    <div
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        { [sty.rooticon_w2]: hasVariant($state, 'icon', 'w2') },
      )}
    >
      {(hasVariant($state, 'icon', '_1099') ? true : true) ? (
        <img
          data-plasmic-name={'img'}
          data-plasmic-override={overrides.img}
          alt={''}
          className={classNames(projectcss.all, projectcss.img, sty.img, {
            [sty.imgicon__1099]: hasVariant($state, 'icon', '_1099'),
          })}
          src={icnW2DfFc8LaUgl}
        />
      ) : null}
      {(hasVariant($state, 'icon', '_1099') ? true : false) ? (
        <div
          data-plasmic-name={'icnChair2'}
          data-plasmic-override={overrides.icnChair2}
          className={classNames(projectcss.all, sty.icnChair2, {
            [sty.icnChair2icon__1099]: hasVariant($state, 'icon', '_1099'),
          })}
        >
          <_1099
            data-plasmic-name={'_1099'}
            data-plasmic-override={overrides._1099}
            className={classNames('__wab_instance', sty._1099)}
          />

          <Group379Icon
            data-plasmic-name={'svg'}
            data-plasmic-override={overrides.svg}
            className={classNames(projectcss.all, sty.svg)}
            role={'img'}
          />
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'img', 'icnChair2', '_1099', 'svg'],
  img: ['img'],
  icnChair2: ['icnChair2', '_1099', 'svg'],
  _1099: ['_1099'],
  svg: ['svg'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  img: 'img';
  icnChair2: 'div';
  _1099: typeof _1099;
  svg: 'svg';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicW2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicW2__VariantsArgs;
    args?: PlasmicW2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicW2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicW2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>,
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicW2__ArgProps,
          internalVariantPropNames: PlasmicW2__VariantProps,
        }),
      [props, nodeName],
    );
    return PlasmicW2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicW2';
  } else {
    func.displayName = `PlasmicW2.${nodeName}`;
  }
  return func;
}

export const PlasmicW2 = Object.assign(
  // Top-level PlasmicW2 renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent('img'),
    icnChair2: makeNodeComponent('icnChair2'),
    _1099: makeNodeComponent('_1099'),
    svg: makeNodeComponent('svg'),

    // Metadata about props expected for PlasmicW2
    internalVariantProps: PlasmicW2__VariantProps,
    internalArgProps: PlasmicW2__ArgProps,
  },
);

export default PlasmicW2;
/* prettier-ignore-end */
