// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ssXJzNt8MiEu8LBoGu8nv3
// Component: UGoV_KYFXN

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import LayoutSplashWithButton from '../../LayoutSplashWithButton'; // plasmic-import: QN6lWZtqTgh/component
import ConfettiBadge from '../../ConfettiBadge'; // plasmic-import: PItJAD3u3f/component
import AltButton from '../../AltButton'; // plasmic-import: 7pGfee8N7aE/component

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_scratch_pad.module.css'; // plasmic-import: ssXJzNt8MiEu8LBoGu8nv3/projectcss
import sty from './PlasmicContentSplashButton2.module.css'; // plasmic-import: UGoV_KYFXN/css

export type PlasmicContentSplashButton2__VariantMembers = {};
export type PlasmicContentSplashButton2__VariantsArgs = {};
type VariantPropType = keyof PlasmicContentSplashButton2__VariantsArgs;
export const PlasmicContentSplashButton2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicContentSplashButton2__ArgsType = {};
type ArgPropType = keyof PlasmicContentSplashButton2__ArgsType;
export const PlasmicContentSplashButton2__ArgProps = new Array<ArgPropType>();

export type PlasmicContentSplashButton2__OverridesType = {
  root?: p.Flex<'div'>;
  layoutSplashWithButton?: p.Flex<typeof LayoutSplashWithButton>;
  nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation?: p.Flex<'div'>;
};

export interface DefaultContentSplashButton2Props {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicContentSplashButton2__RenderFunc(props: {
  variants: PlasmicContentSplashButton2__VariantsArgs;
  args: PlasmicContentSplashButton2__ArgsType;
  overrides: PlasmicContentSplashButton2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
      )}
    >
      <LayoutSplashWithButton
        data-plasmic-name={'layoutSplashWithButton'}
        data-plasmic-override={overrides.layoutSplashWithButton}
        body={
          <div
            data-plasmic-name={
              'nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation'
            }
            data-plasmic-override={
              overrides.nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation
            }
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation,
            )}
          >
            {'Very different'}
          </div>
        }
        className={classNames('__wab_instance', sty.layoutSplashWithButton)}
        title={'Third thing'}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    'root',
    'layoutSplashWithButton',
    'nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation',
  ],
  layoutSplashWithButton: [
    'layoutSplashWithButton',
    'nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation',
  ],
  nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation:
    [
      'nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation',
    ],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  layoutSplashWithButton: typeof LayoutSplashWithButton;
  nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation: 'div';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContentSplashButton2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContentSplashButton2__VariantsArgs;
    args?: PlasmicContentSplashButton2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicContentSplashButton2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicContentSplashButton2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>,
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicContentSplashButton2__ArgProps,
          internalVariantPropNames: PlasmicContentSplashButton2__VariantProps,
        }),
      [props, nodeName],
    );
    return PlasmicContentSplashButton2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicContentSplashButton2';
  } else {
    func.displayName = `PlasmicContentSplashButton2.${nodeName}`;
  }
  return func;
}

export const PlasmicContentSplashButton2 = Object.assign(
  // Top-level PlasmicContentSplashButton2 renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    layoutSplashWithButton: makeNodeComponent('layoutSplashWithButton'),
    nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation:
      makeNodeComponent(
        'nextJustAnswerAFewQuestionsAndWellSetYouUpWithTheRightTaxServiceAndPriceForYourSituation',
      ),

    // Metadata about props expected for PlasmicContentSplashButton2
    internalVariantProps: PlasmicContentSplashButton2__VariantProps,
    internalArgProps: PlasmicContentSplashButton2__ArgProps,
  },
);

export default PlasmicContentSplashButton2;
/* prettier-ignore-end */
