// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ssXJzNt8MiEu8LBoGu8nv3
// Component: eQr-xX-Lwt

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_scratch_pad.module.css'; // plasmic-import: ssXJzNt8MiEu8LBoGu8nv3/projectcss
import sty from './PlasmicProgress.module.css'; // plasmic-import: eQr-xX-Lwt/css

export type PlasmicProgress__VariantMembers = {
  step: '_1' | '_2' | '_3';
};
export type PlasmicProgress__VariantsArgs = {
  step?: SingleChoiceArg<'_1' | '_2' | '_3'>;
};
type VariantPropType = keyof PlasmicProgress__VariantsArgs;
export const PlasmicProgress__VariantProps = new Array<VariantPropType>('step');

export type PlasmicProgress__ArgsType = {};
type ArgPropType = keyof PlasmicProgress__ArgsType;
export const PlasmicProgress__ArgProps = new Array<ArgPropType>();

export type PlasmicProgress__OverridesType = {
  root?: p.Flex<'div'>;
  rectangle290?: p.Flex<'div'>;
  rectangle291?: p.Flex<'div'>;
  rectangle292?: p.Flex<'div'>;
};

export interface DefaultProgressProps {
  step?: SingleChoiceArg<'_1' | '_2' | '_3'>;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicProgress__RenderFunc(props: {
  variants: PlasmicProgress__VariantsArgs;
  args: PlasmicProgress__ArgsType;
  overrides: PlasmicProgress__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: 'step',
        type: 'private',
        variableType: 'variant',
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.step,
      },
    ],
    [$props, $ctx],
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  return (
    <p.Stack
      as={'div'}
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
      )}
    >
      <div
        data-plasmic-name={'rectangle290'}
        data-plasmic-override={overrides.rectangle290}
        className={classNames(projectcss.all, sty.rectangle290)}
      />

      <div
        data-plasmic-name={'rectangle291'}
        data-plasmic-override={overrides.rectangle291}
        className={classNames(projectcss.all, sty.rectangle291, {
          [sty.rectangle291step__2]: hasVariant($state, 'step', '_2'),
          [sty.rectangle291step__3]: hasVariant($state, 'step', '_3'),
        })}
      />

      <div
        data-plasmic-name={'rectangle292'}
        data-plasmic-override={overrides.rectangle292}
        className={classNames(projectcss.all, sty.rectangle292, {
          [sty.rectangle292step__3]: hasVariant($state, 'step', '_3'),
        })}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'rectangle290', 'rectangle291', 'rectangle292'],
  rectangle290: ['rectangle290'],
  rectangle291: ['rectangle291'],
  rectangle292: ['rectangle292'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  rectangle290: 'div';
  rectangle291: 'div';
  rectangle292: 'div';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProgress__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProgress__VariantsArgs;
    args?: PlasmicProgress__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProgress__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicProgress__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>,
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProgress__ArgProps,
          internalVariantPropNames: PlasmicProgress__VariantProps,
        }),
      [props, nodeName],
    );
    return PlasmicProgress__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicProgress';
  } else {
    func.displayName = `PlasmicProgress.${nodeName}`;
  }
  return func;
}

export const PlasmicProgress = Object.assign(
  // Top-level PlasmicProgress renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    rectangle290: makeNodeComponent('rectangle290'),
    rectangle291: makeNodeComponent('rectangle291'),
    rectangle292: makeNodeComponent('rectangle292'),

    // Metadata about props expected for PlasmicProgress
    internalVariantProps: PlasmicProgress__VariantProps,
    internalArgProps: PlasmicProgress__ArgProps,
  },
);

export default PlasmicProgress;
/* prettier-ignore-end */
