// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ssXJzNt8MiEu8LBoGu8nv3
// Component: 6QqebQImju

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_scratch_pad.module.css'; // plasmic-import: ssXJzNt8MiEu8LBoGu8nv3/projectcss
import sty from './PlasmicLayoutSplash.module.css'; // plasmic-import: 6QqebQImju/css

export type PlasmicLayoutSplash__VariantMembers = {};
export type PlasmicLayoutSplash__VariantsArgs = {};
type VariantPropType = keyof PlasmicLayoutSplash__VariantsArgs;
export const PlasmicLayoutSplash__VariantProps = new Array<VariantPropType>();

export type PlasmicLayoutSplash__ArgsType = {
  text?: React.ReactNode;
  img?: React.ReactNode;
};
type ArgPropType = keyof PlasmicLayoutSplash__ArgsType;
export const PlasmicLayoutSplash__ArgProps = new Array<ArgPropType>(
  'text',
  'img',
);

export type PlasmicLayoutSplash__OverridesType = {
  root?: p.Flex<'div'>;
  freeBox?: p.Flex<'div'>;
};

export interface DefaultLayoutSplashProps {
  text?: React.ReactNode;
  img?: React.ReactNode;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicLayoutSplash__RenderFunc(props: {
  variants: PlasmicLayoutSplash__VariantsArgs;
  args: PlasmicLayoutSplash__ArgsType;
  overrides: PlasmicLayoutSplash__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        'page__content' as const,
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents:
          'Nice! You got this, and if you decide you want expert help later, we are here for you.',
        value: args.text,
        className: classNames(sty.slotTargetText),
      })}
      <div
        data-plasmic-name={'freeBox'}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: null,
          value: args.img,
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'freeBox'],
  freeBox: ['freeBox'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  freeBox: 'div';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLayoutSplash__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLayoutSplash__VariantsArgs;
    args?: PlasmicLayoutSplash__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLayoutSplash__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLayoutSplash__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>,
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLayoutSplash__ArgProps,
          internalVariantPropNames: PlasmicLayoutSplash__VariantProps,
        }),
      [props, nodeName],
    );
    return PlasmicLayoutSplash__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicLayoutSplash';
  } else {
    func.displayName = `PlasmicLayoutSplash.${nodeName}`;
  }
  return func;
}

export const PlasmicLayoutSplash = Object.assign(
  // Top-level PlasmicLayoutSplash renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent('freeBox'),

    // Metadata about props expected for PlasmicLayoutSplash
    internalVariantProps: PlasmicLayoutSplash__VariantProps,
    internalArgProps: PlasmicLayoutSplash__ArgProps,
  },
);

export default PlasmicLayoutSplash;
/* prettier-ignore-end */
