// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ssXJzNt8MiEu8LBoGu8nv3
// Component: Aa3yG5k_Fw

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import Thinger from '../../Thinger'; // plasmic-import: wNONG5kdlb/component

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_scratch_pad.module.css'; // plasmic-import: ssXJzNt8MiEu8LBoGu8nv3/projectcss
import sty from './PlasmicRepeater.module.css'; // plasmic-import: Aa3yG5k_Fw/css

export type PlasmicRepeater__VariantMembers = {};
export type PlasmicRepeater__VariantsArgs = {};
type VariantPropType = keyof PlasmicRepeater__VariantsArgs;
export const PlasmicRepeater__VariantProps = new Array<VariantPropType>();

export type PlasmicRepeater__ArgsType = {
  data?: any;
};
type ArgPropType = keyof PlasmicRepeater__ArgsType;
export const PlasmicRepeater__ArgProps = new Array<ArgPropType>('data');

export type PlasmicRepeater__OverridesType = {
  root?: p.Flex<'div'>;
  text?: p.Flex<'div'>;
  thinger?: p.Flex<typeof Thinger>;
};

export interface DefaultRepeaterProps {
  data?: any;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicRepeater__RenderFunc(props: {
  variants: PlasmicRepeater__VariantsArgs;
  args: PlasmicRepeater__ArgsType;
  overrides: PlasmicRepeater__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          data: [
            { title: 'thign 1', green: true },
            { title: 'thign 2' },
            { title: 'thign 3', green: true },
          ],
        },
        props.args,
      ),
    [props.args],
  );

  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
      )}
    >
      <div
        data-plasmic-name={'text'}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {'The title'}
      </div>
      {(
        (() => {
          try {
            return $props.data;
          } catch (e) {
            if (e instanceof TypeError) {
              return [];
            }
            throw e;
          }
        })() ?? []
      ).map((currentItem, currentIndex) => (
        <Thinger
          data-plasmic-name={'thinger'}
          data-plasmic-override={overrides.thinger}
          className={classNames('__wab_instance', sty.thinger)}
          doGreen={(() => {
            try {
              return currentItem.green;
            } catch (e) {
              if (e instanceof TypeError) {
                return false;
              }
              throw e;
            }
          })()}
          key={currentIndex}
          title={(() => {
            try {
              return currentItem.title;
            } catch (e) {
              if (e instanceof TypeError) {
                return undefined;
              }
              throw e;
            }
          })()}
        />
      ))}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'text', 'thinger'],
  text: ['text'],
  thinger: ['thinger'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  text: 'div';
  thinger: typeof Thinger;
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRepeater__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRepeater__VariantsArgs;
    args?: PlasmicRepeater__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRepeater__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicRepeater__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>,
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicRepeater__ArgProps,
          internalVariantPropNames: PlasmicRepeater__VariantProps,
        }),
      [props, nodeName],
    );
    return PlasmicRepeater__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicRepeater';
  } else {
    func.displayName = `PlasmicRepeater.${nodeName}`;
  }
  return func;
}

export const PlasmicRepeater = Object.assign(
  // Top-level PlasmicRepeater renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent('text'),
    thinger: makeNodeComponent('thinger'),

    // Metadata about props expected for PlasmicRepeater
    internalVariantProps: PlasmicRepeater__VariantProps,
    internalArgProps: PlasmicRepeater__ArgProps,
  },
);

export default PlasmicRepeater;
/* prettier-ignore-end */
