// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ssXJzNt8MiEu8LBoGu8nv3
// Component: 61CShZt2qP

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_scratch_pad.module.css'; // plasmic-import: ssXJzNt8MiEu8LBoGu8nv3/projectcss
import sty from './Plasmic_1099.module.css'; // plasmic-import: 61CShZt2qP/css

import Rectangle15Icon from './icons/PlasmicIcon__Rectangle15'; // plasmic-import: TYL9_09ZF5/icon
import Group5Icon from './icons/PlasmicIcon__Group5'; // plasmic-import: txjagnq8oQ/icon
import Stroke6StrokeIcon from './icons/PlasmicIcon__Stroke6Stroke'; // plasmic-import: n_QIwewI32/icon
import Stroke7StrokeIcon from './icons/PlasmicIcon__Stroke7Stroke'; // plasmic-import: rnsDEU_gC7/icon
import Stroke8StrokeIcon from './icons/PlasmicIcon__Stroke8Stroke'; // plasmic-import: Z_7ID_M4Uv/icon
import _1099Icon from './icons/PlasmicIcon___1099'; // plasmic-import: XqfaZNjBQDe/icon
import MiscIcon from './icons/PlasmicIcon__Misc'; // plasmic-import: WbjfJfyqQIu/icon

export type Plasmic_1099__VariantMembers = {};
export type Plasmic_1099__VariantsArgs = {};
type VariantPropType = keyof Plasmic_1099__VariantsArgs;
export const Plasmic_1099__VariantProps = new Array<VariantPropType>();

export type Plasmic_1099__ArgsType = {};
type ArgPropType = keyof Plasmic_1099__ArgsType;
export const Plasmic_1099__ArgProps = new Array<ArgPropType>();

export type Plasmic_1099__OverridesType = {
  root?: p.Flex<'div'>;
  icn1099Form2?: p.Flex<'div'>;
  page1?: p.Flex<'div'>;
};

export interface Default_1099Props {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function Plasmic_1099__RenderFunc(props: {
  variants: Plasmic_1099__VariantsArgs;
  args: Plasmic_1099__ArgsType;
  overrides: Plasmic_1099__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
      )}
    >
      <div
        data-plasmic-name={'icn1099Form2'}
        data-plasmic-override={overrides.icn1099Form2}
        className={classNames(projectcss.all, sty.icn1099Form2)}
      >
        <Rectangle15Icon
          className={classNames(projectcss.all, sty.svg___5Rxom)}
          role={'img'}
        />

        <div
          data-plasmic-name={'page1'}
          data-plasmic-override={overrides.page1}
          className={classNames(projectcss.all, sty.page1)}
        >
          <Group5Icon
            className={classNames(projectcss.all, sty.svg__iMcJa)}
            role={'img'}
          />

          <Stroke6StrokeIcon
            className={classNames(projectcss.all, sty.svg__pTuS)}
            role={'img'}
          />

          <Stroke7StrokeIcon
            className={classNames(projectcss.all, sty.svg__iaOnK)}
            role={'img'}
          />

          <Stroke8StrokeIcon
            className={classNames(projectcss.all, sty.svg__sxhln)}
            role={'img'}
          />
        </div>
        <_1099Icon
          className={classNames(projectcss.all, sty.svg__bEbu6)}
          role={'img'}
        />

        {false ? (
          <MiscIcon
            className={classNames(projectcss.all, sty.svg__x8ZwG)}
            role={'img'}
          />
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'icn1099Form2', 'page1'],
  icn1099Form2: ['icn1099Form2', 'page1'],
  page1: ['page1'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  icn1099Form2: 'div';
  page1: 'div';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic_1099__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic_1099__VariantsArgs;
    args?: Plasmic_1099__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<Plasmic_1099__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      Plasmic_1099__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>,
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: Plasmic_1099__ArgProps,
          internalVariantPropNames: Plasmic_1099__VariantProps,
        }),
      [props, nodeName],
    );
    return Plasmic_1099__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'Plasmic_1099';
  } else {
    func.displayName = `Plasmic_1099.${nodeName}`;
  }
  return func;
}

export const Plasmic_1099 = Object.assign(
  // Top-level Plasmic_1099 renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    icn1099Form2: makeNodeComponent('icn1099Form2'),
    page1: makeNodeComponent('page1'),

    // Metadata about props expected for Plasmic_1099
    internalVariantProps: Plasmic_1099__VariantProps,
    internalArgProps: Plasmic_1099__ArgProps,
  },
);

export default Plasmic_1099;
/* prettier-ignore-end */
