// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ssXJzNt8MiEu8LBoGu8nv3
// Component: xl-_9c6wX3

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';

import { useScreenVariants as useScreenVariantswltrMaZg3P3 } from './PlasmicGlobalVariant__Screen'; // plasmic-import: WltrMa_Zg3p3/globalVariant

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_scratch_pad.module.css'; // plasmic-import: ssXJzNt8MiEu8LBoGu8nv3/projectcss
import sty from './PlasmicBlueSkyPageContent1.module.css'; // plasmic-import: xl-_9c6wX3/css

import sceneCelebrationDuPb0HkBhE from './images/sceneCelebration.svg'; // plasmic-import: duPB0HkBhE/picture

export type PlasmicBlueSkyPageContent1__VariantMembers = {};
export type PlasmicBlueSkyPageContent1__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlueSkyPageContent1__VariantsArgs;
export const PlasmicBlueSkyPageContent1__VariantProps =
  new Array<VariantPropType>();

export type PlasmicBlueSkyPageContent1__ArgsType = {};
type ArgPropType = keyof PlasmicBlueSkyPageContent1__ArgsType;
export const PlasmicBlueSkyPageContent1__ArgProps = new Array<ArgPropType>();

export type PlasmicBlueSkyPageContent1__OverridesType = {
  root?: p.Flex<'div'>;
  freeBox?: p.Flex<'div'>;
  h2?: p.Flex<'h2'>;
  text?: p.Flex<'div'>;
  img?: p.Flex<'img'>;
};

export interface DefaultBlueSkyPageContent1Props {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicBlueSkyPageContent1__RenderFunc(props: {
  variants: PlasmicBlueSkyPageContent1__VariantsArgs;
  args: PlasmicBlueSkyPageContent1__ArgsType;
  overrides: PlasmicBlueSkyPageContent1__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswltrMaZg3P3(),
  });

  return (
    <div
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
      )}
    >
      {true ? (
        <div
          data-plasmic-name={'freeBox'}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          <h2
            data-plasmic-name={'h2'}
            data-plasmic-override={overrides.h2}
            className={classNames(
              projectcss.all,
              projectcss.h2,
              projectcss.__wab_text,
              sty.h2,
            )}
          >
            {'File smarter'}
          </h2>
          <div
            data-plasmic-name={'text'}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text,
            )}
          >
            {'Add your forms to jump start your taxes'}
          </div>
        </div>
      ) : null}
      <img
        data-plasmic-name={'img'}
        data-plasmic-override={overrides.img}
        alt={''}
        className={classNames(projectcss.all, projectcss.img, sty.img)}
        loading={'lazy' as const}
        src={sceneCelebrationDuPb0HkBhE}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'freeBox', 'h2', 'text', 'img'],
  freeBox: ['freeBox', 'h2', 'text'],
  h2: ['h2'],
  text: ['text'],
  img: ['img'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  freeBox: 'div';
  h2: 'h2';
  text: 'div';
  img: 'img';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlueSkyPageContent1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlueSkyPageContent1__VariantsArgs;
    args?: PlasmicBlueSkyPageContent1__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlueSkyPageContent1__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBlueSkyPageContent1__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>,
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBlueSkyPageContent1__ArgProps,
          internalVariantPropNames: PlasmicBlueSkyPageContent1__VariantProps,
        }),
      [props, nodeName],
    );
    return PlasmicBlueSkyPageContent1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicBlueSkyPageContent1';
  } else {
    func.displayName = `PlasmicBlueSkyPageContent1.${nodeName}`;
  }
  return func;
}

export const PlasmicBlueSkyPageContent1 = Object.assign(
  // Top-level PlasmicBlueSkyPageContent1 renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent('freeBox'),
    h2: makeNodeComponent('h2'),
    text: makeNodeComponent('text'),
    img: makeNodeComponent('img'),

    // Metadata about props expected for PlasmicBlueSkyPageContent1
    internalVariantProps: PlasmicBlueSkyPageContent1__VariantProps,
    internalArgProps: PlasmicBlueSkyPageContent1__ArgProps,
  },
);

export default PlasmicBlueSkyPageContent1;
/* prettier-ignore-end */
