// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bWL5f4gAFbwKhEp4ZCgaRf
// Component: utaTr6t3GO
import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_mar_tech_atoms.module.css'; // plasmic-import: bWL5f4gAFbwKhEp4ZCgaRf/projectcss
import sty from './PlasmicStarRating.module.css'; // plasmic-import: utaTr6t3GO/css

import StarIcon from './icons/PlasmicIcon__Star'; // plasmic-import: 14w9HZUPy/icon

export type PlasmicStarRating__VariantMembers = {
  justify: 'left' | 'center';
  align: 'row' | 'rowWhite' | 'inline';
  color: 'white';
  size: 'small';
  disclaimerIndicator: 'asterisk';
};
export type PlasmicStarRating__VariantsArgs = {
  justify?: SingleChoiceArg<'left' | 'center'>;
  align?: SingleChoiceArg<'row' | 'rowWhite' | 'inline'>;
  color?: SingleChoiceArg<'white'>;
  size?: SingleChoiceArg<'small'>;
  disclaimerIndicator?: MultiChoiceArg<'asterisk'>;
};
type VariantPropType = keyof PlasmicStarRating__VariantsArgs;
export const PlasmicStarRating__VariantProps = new Array<VariantPropType>(
  'justify',
  'align',
  'color',
  'size',
  'disclaimerIndicator',
);

export type PlasmicStarRating__ArgsType = {
  text?: React.ReactNode;
  disclaimerText?: React.ReactNode;
};
type ArgPropType = keyof PlasmicStarRating__ArgsType;
export const PlasmicStarRating__ArgProps = new Array<ArgPropType>(
  'text',
  'disclaimerText',
);

export type PlasmicStarRating__OverridesType = {
  root?: p.Flex<'button'>;
  starWrapper?: p.Flex<'div'>;
  baseStarWrapper?: p.Flex<'div'>;
  colorStarWrapper?: p.Flex<'div'>;
  textWrapper?: p.Flex<'div'>;
};

export interface DefaultStarRatingProps {
  text?: React.ReactNode;
  disclaimerText?: React.ReactNode;
  justify?: SingleChoiceArg<'left' | 'center'>;
  align?: SingleChoiceArg<'row' | 'rowWhite' | 'inline'>;
  color?: SingleChoiceArg<'white'>;
  size?: SingleChoiceArg<'small'>;
  disclaimerIndicator?: MultiChoiceArg<'asterisk'>;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicStarRating__RenderFunc(props: {
  variants: PlasmicStarRating__VariantsArgs;
  args: PlasmicStarRating__ArgsType;
  overrides: PlasmicStarRating__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: 'justify',
        type: 'private',
        variableType: 'variant',
        initFunc: true
          ? ({ $props, $state, $queries, $ctx }) => $props.justify
          : undefined,
      },
      {
        path: 'align',
        type: 'private',
        variableType: 'variant',
        initFunc: true
          ? ({ $props, $state, $queries, $ctx }) => $props.align
          : undefined,
      },
      {
        path: 'color',
        type: 'private',
        variableType: 'variant',
        initFunc: true
          ? ({ $props, $state, $queries, $ctx }) => $props.color
          : undefined,
      },
      {
        path: 'size',
        type: 'private',
        variableType: 'variant',
        initFunc: true
          ? ({ $props, $state, $queries, $ctx }) => $props.size
          : undefined,
      },
      {
        path: 'disclaimerIndicator',
        type: 'private',
        variableType: 'variant',
        initFunc: true
          ? ({ $props, $state, $queries, $ctx }) => $props.disclaimerIndicator
          : undefined,
      },
    ],
    [$props, $ctx],
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  return (
    <p.Stack
      as={'button'}
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootalign_inline]: hasVariant($state, 'align', 'inline'),
          [sty.rootalign_inline_color_white]:
            hasVariant($state, 'align', 'inline') &&
            hasVariant($state, 'color', 'white'),
          [sty.rootalign_inline_color_white_justify_center]:
            hasVariant($state, 'justify', 'center') &&
            hasVariant($state, 'align', 'inline') &&
            hasVariant($state, 'color', 'white'),
          [sty.rootalign_inline_justify_center]:
            hasVariant($state, 'align', 'inline') &&
            hasVariant($state, 'justify', 'center'),
          [sty.rootalign_rowWhite]: hasVariant($state, 'align', 'rowWhite'),
          [sty.rootalign_row]: hasVariant($state, 'align', 'row'),
          [sty.rootjustify_center]: hasVariant($state, 'justify', 'center'),
          [sty.rootjustify_left]: hasVariant($state, 'justify', 'left'),
        },
      )}
    >
      <p.Stack
        as={'div'}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__mDgol, {
          [sty.freeBoxalign_inline__mDgol0E4VE]: hasVariant(
            $state,
            'align',
            'inline',
          ),
          [sty.freeBoxalign_rowWhite__mDgoLm4Ssp]: hasVariant(
            $state,
            'align',
            'rowWhite',
          ),
          [sty.freeBoxalign_row__mDgold0Cee]: hasVariant(
            $state,
            'align',
            'row',
          ),
          [sty.freeBoxalign_row_size_small__mDgold0CeeVxj0O]:
            hasVariant($state, 'align', 'row') &&
            hasVariant($state, 'size', 'small'),
          [sty.freeBoxcolor_white__mDgolCxdUz]: hasVariant(
            $state,
            'color',
            'white',
          ),
          [sty.freeBoxjustify_center__mDgoLvjzZr]: hasVariant(
            $state,
            'justify',
            'center',
          ),
          [sty.freeBoxjustify_left__mDgoluXjyY]: hasVariant(
            $state,
            'justify',
            'left',
          ),
        })}
      >
        <div
          data-plasmic-name={'starWrapper'}
          data-plasmic-override={overrides.starWrapper}
          className={classNames(projectcss.all, sty.starWrapper, {
            [sty.starWrapperalign_inline]: hasVariant(
              $state,
              'align',
              'inline',
            ),
            [sty.starWrapperalign_rowWhite]: hasVariant(
              $state,
              'align',
              'rowWhite',
            ),
            [sty.starWrapperalign_row]: hasVariant($state, 'align', 'row'),
            [sty.starWrapperjustify_left]: hasVariant(
              $state,
              'justify',
              'left',
            ),
          })}
        >
          {true ? (
            <p.Stack
              as={'div'}
              data-plasmic-name={'baseStarWrapper'}
              data-plasmic-override={overrides.baseStarWrapper}
              hasGap={true}
              className={classNames(projectcss.all, sty.baseStarWrapper, {
                [sty.baseStarWrapperalign_inline]: hasVariant(
                  $state,
                  'align',
                  'inline',
                ),
                [sty.baseStarWrapperalign_row]: hasVariant(
                  $state,
                  'align',
                  'row',
                ),
                [sty.baseStarWrapperjustify_left]: hasVariant(
                  $state,
                  'justify',
                  'left',
                ),
                [sty.baseStarWrappersize_small]: hasVariant(
                  $state,
                  'size',
                  'small',
                ),
              })}
            >
              {true ? (
                <StarIcon
                  aria-hidden={'true' as const}
                  className={classNames(projectcss.all, sty.svg__qv5Fz, {
                    [sty.svgsize_small__qv5FzVxj0O]: hasVariant(
                      $state,
                      'size',
                      'small',
                    ),
                  })}
                  role={'img'}
                />
              ) : null}

              <StarIcon
                aria-hidden={'true' as const}
                className={classNames(projectcss.all, sty.svg__hHpRm, {
                  [sty.svgsize_small__hHpRmVxj0O]: hasVariant(
                    $state,
                    'size',
                    'small',
                  ),
                })}
                role={'img'}
              />

              <StarIcon
                aria-hidden={'true' as const}
                className={classNames(projectcss.all, sty.svg__llMh1, {
                  [sty.svgalign_inline__llMh10E4VE]: hasVariant(
                    $state,
                    'align',
                    'inline',
                  ),
                  [sty.svgsize_small__llMh1Vxj0O]: hasVariant(
                    $state,
                    'size',
                    'small',
                  ),
                })}
                role={'img'}
              />

              <StarIcon
                aria-hidden={'true' as const}
                className={classNames(projectcss.all, sty.svg___7NHIf, {
                  [sty.svgalign_inline___7NHIf0E4VE]: hasVariant(
                    $state,
                    'align',
                    'inline',
                  ),
                  [sty.svgjustify_left___7NHIfUXjyY]: hasVariant(
                    $state,
                    'justify',
                    'left',
                  ),
                  [sty.svgsize_small___7NHIfVxj0O]: hasVariant(
                    $state,
                    'size',
                    'small',
                  ),
                })}
                role={'img'}
              />

              <StarIcon
                aria-hidden={'true' as const}
                className={classNames(projectcss.all, sty.svg__vbTBc, {
                  [sty.svgalign_row__vbTBcD0Cee]: hasVariant(
                    $state,
                    'align',
                    'row',
                  ),
                  [sty.svgsize_small__vbTBcVxj0O]: hasVariant(
                    $state,
                    'size',
                    'small',
                  ),
                })}
                role={'img'}
              />
            </p.Stack>
          ) : null}

          <p.Stack
            as={'div'}
            data-plasmic-name={'colorStarWrapper'}
            data-plasmic-override={overrides.colorStarWrapper}
            hasGap={true}
            className={classNames(projectcss.all, sty.colorStarWrapper, {
              [sty.colorStarWrapperalign_inline]: hasVariant(
                $state,
                'align',
                'inline',
              ),
              [sty.colorStarWrapperalign_rowWhite]: hasVariant(
                $state,
                'align',
                'rowWhite',
              ),
              [sty.colorStarWrapperalign_row]: hasVariant(
                $state,
                'align',
                'row',
              ),
              [sty.colorStarWrapperjustify_center]: hasVariant(
                $state,
                'justify',
                'center',
              ),
              [sty.colorStarWrapperjustify_left]: hasVariant(
                $state,
                'justify',
                'left',
              ),
            })}
          >
            <StarIcon
              aria-hidden={'true' as const}
              className={classNames(projectcss.all, sty.svg__o5Fm, {
                [sty.svgalign_inline__o5Fm0E4VE]: hasVariant(
                  $state,
                  'align',
                  'inline',
                ),
                [sty.svgalign_rowWhite__o5Fmm4Ssp]: hasVariant(
                  $state,
                  'align',
                  'rowWhite',
                ),
                [sty.svgalign_row__o5FmD0Cee]: hasVariant(
                  $state,
                  'align',
                  'row',
                ),
                [sty.svgcolor_white__o5FmCxdUz]: hasVariant(
                  $state,
                  'color',
                  'white',
                ),
                [sty.svgjustify_left__o5FmUXjyY]: hasVariant(
                  $state,
                  'justify',
                  'left',
                ),
                [sty.svgsize_small__o5FmVxj0O]: hasVariant(
                  $state,
                  'size',
                  'small',
                ),
              })}
              role={'img'}
            />

            <StarIcon
              aria-hidden={'true' as const}
              className={classNames(projectcss.all, sty.svg___96HE, {
                [sty.svgalign_inline___96HE0E4VE]: hasVariant(
                  $state,
                  'align',
                  'inline',
                ),
                [sty.svgalign_rowWhite___96HEm4Ssp]: hasVariant(
                  $state,
                  'align',
                  'rowWhite',
                ),
                [sty.svgjustify_center___96HEvjzZr]: hasVariant(
                  $state,
                  'justify',
                  'center',
                ),
                [sty.svgjustify_left___96HEuXjyY]: hasVariant(
                  $state,
                  'justify',
                  'left',
                ),
                [sty.svgsize_small___96HEvxj0O]: hasVariant(
                  $state,
                  'size',
                  'small',
                ),
              })}
              role={'img'}
            />

            <StarIcon
              aria-hidden={'true' as const}
              className={classNames(projectcss.all, sty.svg__muCUo, {
                [sty.svgjustify_left__muCUoUXjyY]: hasVariant(
                  $state,
                  'justify',
                  'left',
                ),
                [sty.svgsize_small__muCUoVxj0O]: hasVariant(
                  $state,
                  'size',
                  'small',
                ),
              })}
              role={'img'}
            />

            <StarIcon
              aria-hidden={'true' as const}
              className={classNames(projectcss.all, sty.svg___2CaHl, {
                [sty.svgsize_small___2CaHlvxj0O]: hasVariant(
                  $state,
                  'size',
                  'small',
                ),
              })}
              role={'img'}
            />

            <StarIcon
              aria-hidden={'true' as const}
              className={classNames(projectcss.all, sty.svg__mtVqu, {
                [sty.svgcolor_white__mtVquCxdUz]: hasVariant(
                  $state,
                  'color',
                  'white',
                ),
                [sty.svgsize_small__mtVquVxj0O]: hasVariant(
                  $state,
                  'size',
                  'small',
                ),
              })}
              role={'img'}
            />
          </p.Stack>
        </div>

        <div
          data-plasmic-name={'textWrapper'}
          data-plasmic-override={overrides.textWrapper}
          className={classNames(projectcss.all, sty.textWrapper, {
            [sty.textWrapperalign_inline]: hasVariant(
              $state,
              'align',
              'inline',
            ),
            [sty.textWrapperalign_rowWhite]: hasVariant(
              $state,
              'align',
              'rowWhite',
            ),
            [sty.textWrapperalign_row]: hasVariant($state, 'align', 'row'),
            [sty.textWrapperdisclaimerIndicator_asterisk]: hasVariant(
              $state,
              'disclaimerIndicator',
              'asterisk',
            ),
            [sty.textWrapperjustify_left]: hasVariant(
              $state,
              'justify',
              'left',
            ),
            [sty.textWrappersize_small]: hasVariant($state, 'size', 'small'),
          })}
        >
          {true
            ? p.renderPlasmicSlot({
                defaultContents: <p.Trans>{'text'}</p.Trans>,
                value: args.text,
                className: classNames(sty.slotTargetText, {
                  [sty.slotTargetTextalign_rowWhite]: hasVariant(
                    $state,
                    'align',
                    'rowWhite',
                  ),
                  [sty.slotTargetTextalign_row]: hasVariant(
                    $state,
                    'align',
                    'row',
                  ),
                  [sty.slotTargetTextcolor_white]: hasVariant(
                    $state,
                    'color',
                    'white',
                  ),
                  [sty.slotTargetTextdisclaimerIndicator_asterisk]: hasVariant(
                    $state,
                    'disclaimerIndicator',
                    'asterisk',
                  ),
                  [sty.slotTargetTextjustify_left]: hasVariant(
                    $state,
                    'justify',
                    'left',
                  ),
                  [sty.slotTargetTextsize_small]: hasVariant(
                    $state,
                    'size',
                    'small',
                  ),
                }),
              })
            : null}
          {(
            hasVariant($state, 'disclaimerIndicator', 'asterisk') ? true : true
          ) ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kIdmP,
                {
                  [sty.textdisclaimerIndicator_asterisk__kIdmPt6Bp0]:
                    hasVariant($state, 'disclaimerIndicator', 'asterisk'),
                  [sty.textsize_small__kIdmPvxj0O]: hasVariant(
                    $state,
                    'size',
                    'small',
                  ),
                },
              )}
            >
              <p.Trans>
                {hasVariant($state, 'disclaimerIndicator', 'asterisk')
                  ? '**'
                  : 'text'}
              </p.Trans>
            </div>
          ) : null}
        </div>
      </p.Stack>

      <div
        className={classNames(projectcss.all, sty.freeBox__y8Ga, {
          [sty.freeBoxalign_inline__y8Ga0E4VE]: hasVariant(
            $state,
            'align',
            'inline',
          ),
          [sty.freeBoxalign_inline_color_white__y8Ga0E4VECxdUz]:
            hasVariant($state, 'align', 'inline') &&
            hasVariant($state, 'color', 'white'),
          [sty.freeBoxalign_rowWhite__y8GaM4Ssp]: hasVariant(
            $state,
            'align',
            'rowWhite',
          ),
          [sty.freeBoxalign_row__y8GaD0Cee]: hasVariant($state, 'align', 'row'),
          [sty.freeBoxjustify_left__y8GaUXjyY]: hasVariant(
            $state,
            'justify',
            'left',
          ),
        })}
      >
        {(hasVariant($state, 'align', 'rowWhite') ? true : true)
          ? p.renderPlasmicSlot({
              defaultContents: (
                <p.Trans>{'Star ratings are from 20XX'}</p.Trans>
              ),
              value: args.disclaimerText,
              className: classNames(sty.slotTargetDisclaimerText, {
                [sty.slotTargetDisclaimerTextalign_inline]: hasVariant(
                  $state,
                  'align',
                  'inline',
                ),
                [sty.slotTargetDisclaimerTextalign_inline_color_white]:
                  hasVariant($state, 'align', 'inline') &&
                  hasVariant($state, 'color', 'white'),
                [sty.slotTargetDisclaimerTextalign_inline_color_white_justify_center]:
                  hasVariant($state, 'justify', 'center') &&
                  hasVariant($state, 'align', 'inline') &&
                  hasVariant($state, 'color', 'white'),
                [sty.slotTargetDisclaimerTextalign_rowWhite]: hasVariant(
                  $state,
                  'align',
                  'rowWhite',
                ),
                [sty.slotTargetDisclaimerTextalign_row]: hasVariant(
                  $state,
                  'align',
                  'row',
                ),
                [sty.slotTargetDisclaimerTextcolor_white]: hasVariant(
                  $state,
                  'color',
                  'white',
                ),
                [sty.slotTargetDisclaimerTextjustify_center]: hasVariant(
                  $state,
                  'justify',
                  'center',
                ),
                [sty.slotTargetDisclaimerTextjustify_left]: hasVariant(
                  $state,
                  'justify',
                  'left',
                ),
              }),
            })
          : null}
        {(
          hasVariant($state, 'align', 'inline') &&
          hasVariant($state, 'color', 'white')
            ? true
            : hasVariant($state, 'align', 'rowWhite')
            ? true
            : false
        ) ? (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__oIxFy,
              {
                [sty.textalign_inline__oIxFy0E4VE]: hasVariant(
                  $state,
                  'align',
                  'inline',
                ),
                [sty.textalign_inline_color_white__oIxFy0E4VECxdUz]:
                  hasVariant($state, 'align', 'inline') &&
                  hasVariant($state, 'color', 'white'),
                [sty.textalign_rowWhite__oIxFym4Ssp]: hasVariant(
                  $state,
                  'align',
                  'rowWhite',
                ),
              },
            )}
          >
            <p.Trans>
              {hasVariant($state, 'align', 'rowWhite')
                ? 'Star ratings are from 2021'
                : 'Enter some text'}
            </p.Trans>
          </div>
        ) : null}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    'root',
    'starWrapper',
    'baseStarWrapper',
    'colorStarWrapper',
    'textWrapper',
  ],
  starWrapper: ['starWrapper', 'baseStarWrapper', 'colorStarWrapper'],
  baseStarWrapper: ['baseStarWrapper'],
  colorStarWrapper: ['colorStarWrapper'],
  textWrapper: ['textWrapper'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'button';
  starWrapper: 'div';
  baseStarWrapper: 'div';
  colorStarWrapper: 'div';
  textWrapper: 'div';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStarRating__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStarRating__VariantsArgs;
    args?: PlasmicStarRating__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStarRating__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicStarRating__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>,
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicStarRating__ArgProps,
          internalVariantPropNames: PlasmicStarRating__VariantProps,
        }),
      [props, nodeName],
    );

    return PlasmicStarRating__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicStarRating';
  } else {
    func.displayName = `PlasmicStarRating.${nodeName}`;
  }
  return func;
}

export const PlasmicStarRating = Object.assign(
  // Top-level PlasmicStarRating renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    starWrapper: makeNodeComponent('starWrapper'),
    baseStarWrapper: makeNodeComponent('baseStarWrapper'),
    colorStarWrapper: makeNodeComponent('colorStarWrapper'),
    textWrapper: makeNodeComponent('textWrapper'),

    // Metadata about props expected for PlasmicStarRating
    internalVariantProps: PlasmicStarRating__VariantProps,
    internalArgProps: PlasmicStarRating__ArgProps,
  },
);

export default PlasmicStarRating;
/* prettier-ignore-end */
